// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Li24/struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Li24_2fstruct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Li24_2fstruct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "crypto-suites/crypto-curve/proto_gen/curve_point.pb.switch.h"
#include "crypto-suites/crypto-paillier/proto_gen/paillier.pb.switch.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Li24_2fstruct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Li24_2fstruct_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Li24_2fstruct_2eproto;
namespace safeheron {
namespace proto {
namespace multi_party_ecdsa {
namespace Li24 {
class Party;
class PartyDefaultTypeInternal;
extern PartyDefaultTypeInternal _Party_default_instance_;
class SignKey;
class SignKeyDefaultTypeInternal;
extern SignKeyDefaultTypeInternal _SignKey_default_instance_;
}  // namespace Li24
}  // namespace multi_party_ecdsa
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> ::safeheron::proto::multi_party_ecdsa::Li24::Party* Arena::CreateMaybeMessage<::safeheron::proto::multi_party_ecdsa::Li24::Party>(Arena*);
template<> ::safeheron::proto::multi_party_ecdsa::Li24::SignKey* Arena::CreateMaybeMessage<::safeheron::proto::multi_party_ecdsa::Li24::SignKey>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace safeheron {
namespace proto {
namespace multi_party_ecdsa {
namespace Li24 {

// ===================================================================

class Party PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.multi_party_ecdsa.Li24.Party) */ {
 public:
  inline Party() : Party(nullptr) {}
  virtual ~Party();

  Party(const Party& from);
  Party(Party&& from) noexcept
    : Party() {
    *this = ::std::move(from);
  }

  inline Party& operator=(const Party& from) {
    CopyFrom(from);
    return *this;
  }
  inline Party& operator=(Party&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Party& default_instance();

  static inline const Party* internal_default_instance() {
    return reinterpret_cast<const Party*>(
               &_Party_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Party& a, Party& b) {
    a.Swap(&b);
  }
  inline void Swap(Party* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Party* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Party* New() const final {
    return CreateMaybeMessage<Party>(nullptr);
  }

  Party* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Party>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Party& from);
  void MergeFrom(const Party& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Party* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.multi_party_ecdsa.Li24.Party";
  }
  protected:
  explicit Party(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Li24_2fstruct_2eproto);
    return ::descriptor_table_Li24_2fstruct_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSeedFieldNumber = 10,
    kPartyIdFieldNumber = 1,
    kIndexFieldNumber = 3,
    kXFieldNumber = 8,
    kGXFieldNumber = 9,
  };
  // repeated string seed = 10;
  int seed_size() const;
  private:
  int _internal_seed_size() const;
  public:
  void clear_seed();
  const std::string& seed(int index) const;
  std::string* mutable_seed(int index);
  void set_seed(int index, const std::string& value);
  void set_seed(int index, std::string&& value);
  void set_seed(int index, const char* value);
  void set_seed(int index, const char* value, size_t size);
  std::string* add_seed();
  void add_seed(const std::string& value);
  void add_seed(std::string&& value);
  void add_seed(const char* value);
  void add_seed(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& seed() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_seed();
  private:
  const std::string& _internal_seed(int index) const;
  std::string* _internal_add_seed();
  public:

  // string party_id = 1;
  void clear_party_id();
  const std::string& party_id() const;
  void set_party_id(const std::string& value);
  void set_party_id(std::string&& value);
  void set_party_id(const char* value);
  void set_party_id(const char* value, size_t size);
  std::string* mutable_party_id();
  std::string* release_party_id();
  void set_allocated_party_id(std::string* party_id);
  private:
  const std::string& _internal_party_id() const;
  void _internal_set_party_id(const std::string& value);
  std::string* _internal_mutable_party_id();
  public:

  // string index = 3;
  void clear_index();
  const std::string& index() const;
  void set_index(const std::string& value);
  void set_index(std::string&& value);
  void set_index(const char* value);
  void set_index(const char* value, size_t size);
  std::string* mutable_index();
  std::string* release_index();
  void set_allocated_index(std::string* index);
  private:
  const std::string& _internal_index() const;
  void _internal_set_index(const std::string& value);
  std::string* _internal_mutable_index();
  public:

  // string x = 8;
  void clear_x();
  const std::string& x() const;
  void set_x(const std::string& value);
  void set_x(std::string&& value);
  void set_x(const char* value);
  void set_x(const char* value, size_t size);
  std::string* mutable_x();
  std::string* release_x();
  void set_allocated_x(std::string* x);
  private:
  const std::string& _internal_x() const;
  void _internal_set_x(const std::string& value);
  std::string* _internal_mutable_x();
  public:

  // .safeheron.proto.CurvePoint g_x = 9;
  bool has_g_x() const;
  private:
  bool _internal_has_g_x() const;
  public:
  void clear_g_x();
  const ::safeheron::proto::CurvePoint& g_x() const;
  ::safeheron::proto::CurvePoint* release_g_x();
  ::safeheron::proto::CurvePoint* mutable_g_x();
  void set_allocated_g_x(::safeheron::proto::CurvePoint* g_x);
  private:
  const ::safeheron::proto::CurvePoint& _internal_g_x() const;
  ::safeheron::proto::CurvePoint* _internal_mutable_g_x();
  public:
  void unsafe_arena_set_allocated_g_x(
      ::safeheron::proto::CurvePoint* g_x);
  ::safeheron::proto::CurvePoint* unsafe_arena_release_g_x();

  // @@protoc_insertion_point(class_scope:safeheron.proto.multi_party_ecdsa.Li24.Party)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> seed_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr party_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr index_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr x_;
  ::safeheron::proto::CurvePoint* g_x_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Li24_2fstruct_2eproto;
};
// -------------------------------------------------------------------

class SignKey PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.multi_party_ecdsa.Li24.SignKey) */ {
 public:
  inline SignKey() : SignKey(nullptr) {}
  virtual ~SignKey();

  SignKey(const SignKey& from);
  SignKey(SignKey&& from) noexcept
    : SignKey() {
    *this = ::std::move(from);
  }

  inline SignKey& operator=(const SignKey& from) {
    CopyFrom(from);
    return *this;
  }
  inline SignKey& operator=(SignKey&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SignKey& default_instance();

  static inline const SignKey* internal_default_instance() {
    return reinterpret_cast<const SignKey*>(
               &_SignKey_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SignKey& a, SignKey& b) {
    a.Swap(&b);
  }
  inline void Swap(SignKey* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignKey* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SignKey* New() const final {
    return CreateMaybeMessage<SignKey>(nullptr);
  }

  SignKey* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SignKey>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SignKey& from);
  void MergeFrom(const SignKey& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SignKey* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.multi_party_ecdsa.Li24.SignKey";
  }
  protected:
  explicit SignKey(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Li24_2fstruct_2eproto);
    return ::descriptor_table_Li24_2fstruct_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRemotePartiesFieldNumber = 6,
    kWorkspaceIdFieldNumber = 1,
    kLocalPartyFieldNumber = 5,
    kGXFieldNumber = 7,
    kThresholdFieldNumber = 2,
    kNPartiesFieldNumber = 3,
  };
  // repeated .safeheron.proto.multi_party_ecdsa.Li24.Party remote_parties = 6;
  int remote_parties_size() const;
  private:
  int _internal_remote_parties_size() const;
  public:
  void clear_remote_parties();
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* mutable_remote_parties(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::safeheron::proto::multi_party_ecdsa::Li24::Party >*
      mutable_remote_parties();
  private:
  const ::safeheron::proto::multi_party_ecdsa::Li24::Party& _internal_remote_parties(int index) const;
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* _internal_add_remote_parties();
  public:
  const ::safeheron::proto::multi_party_ecdsa::Li24::Party& remote_parties(int index) const;
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* add_remote_parties();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::safeheron::proto::multi_party_ecdsa::Li24::Party >&
      remote_parties() const;

  // string workspace_id = 1;
  void clear_workspace_id();
  const std::string& workspace_id() const;
  void set_workspace_id(const std::string& value);
  void set_workspace_id(std::string&& value);
  void set_workspace_id(const char* value);
  void set_workspace_id(const char* value, size_t size);
  std::string* mutable_workspace_id();
  std::string* release_workspace_id();
  void set_allocated_workspace_id(std::string* workspace_id);
  private:
  const std::string& _internal_workspace_id() const;
  void _internal_set_workspace_id(const std::string& value);
  std::string* _internal_mutable_workspace_id();
  public:

  // .safeheron.proto.multi_party_ecdsa.Li24.Party local_party = 5;
  bool has_local_party() const;
  private:
  bool _internal_has_local_party() const;
  public:
  void clear_local_party();
  const ::safeheron::proto::multi_party_ecdsa::Li24::Party& local_party() const;
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* release_local_party();
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* mutable_local_party();
  void set_allocated_local_party(::safeheron::proto::multi_party_ecdsa::Li24::Party* local_party);
  private:
  const ::safeheron::proto::multi_party_ecdsa::Li24::Party& _internal_local_party() const;
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* _internal_mutable_local_party();
  public:
  void unsafe_arena_set_allocated_local_party(
      ::safeheron::proto::multi_party_ecdsa::Li24::Party* local_party);
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* unsafe_arena_release_local_party();

  // .safeheron.proto.CurvePoint g_x = 7;
  bool has_g_x() const;
  private:
  bool _internal_has_g_x() const;
  public:
  void clear_g_x();
  const ::safeheron::proto::CurvePoint& g_x() const;
  ::safeheron::proto::CurvePoint* release_g_x();
  ::safeheron::proto::CurvePoint* mutable_g_x();
  void set_allocated_g_x(::safeheron::proto::CurvePoint* g_x);
  private:
  const ::safeheron::proto::CurvePoint& _internal_g_x() const;
  ::safeheron::proto::CurvePoint* _internal_mutable_g_x();
  public:
  void unsafe_arena_set_allocated_g_x(
      ::safeheron::proto::CurvePoint* g_x);
  ::safeheron::proto::CurvePoint* unsafe_arena_release_g_x();

  // int32 threshold = 2;
  void clear_threshold();
  ::PROTOBUF_NAMESPACE_ID::int32 threshold() const;
  void set_threshold(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_threshold() const;
  void _internal_set_threshold(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 n_parties = 3;
  void clear_n_parties();
  ::PROTOBUF_NAMESPACE_ID::int32 n_parties() const;
  void set_n_parties(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_n_parties() const;
  void _internal_set_n_parties(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.multi_party_ecdsa.Li24.SignKey)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::safeheron::proto::multi_party_ecdsa::Li24::Party > remote_parties_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr workspace_id_;
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* local_party_;
  ::safeheron::proto::CurvePoint* g_x_;
  ::PROTOBUF_NAMESPACE_ID::int32 threshold_;
  ::PROTOBUF_NAMESPACE_ID::int32 n_parties_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Li24_2fstruct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Party

// string party_id = 1;
inline void Party::clear_party_id() {
  party_id_.ClearToEmpty();
}
inline const std::string& Party::party_id() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
  return _internal_party_id();
}
inline void Party::set_party_id(const std::string& value) {
  _internal_set_party_id(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
}
inline std::string* Party::mutable_party_id() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
  return _internal_mutable_party_id();
}
inline const std::string& Party::_internal_party_id() const {
  return party_id_.Get();
}
inline void Party::_internal_set_party_id(const std::string& value) {
  
  party_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Party::set_party_id(std::string&& value) {
  
  party_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
}
inline void Party::set_party_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  party_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
}
inline void Party::set_party_id(const char* value,
    size_t size) {
  
  party_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
}
inline std::string* Party::_internal_mutable_party_id() {
  
  return party_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Party::release_party_id() {
  // @@protoc_insertion_point(field_release:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
  return party_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Party::set_allocated_party_id(std::string* party_id) {
  if (party_id != nullptr) {
    
  } else {
    
  }
  party_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), party_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.Party.party_id)
}

// string index = 3;
inline void Party::clear_index() {
  index_.ClearToEmpty();
}
inline const std::string& Party::index() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
  return _internal_index();
}
inline void Party::set_index(const std::string& value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
}
inline std::string* Party::mutable_index() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
  return _internal_mutable_index();
}
inline const std::string& Party::_internal_index() const {
  return index_.Get();
}
inline void Party::_internal_set_index(const std::string& value) {
  
  index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Party::set_index(std::string&& value) {
  
  index_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
}
inline void Party::set_index(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
}
inline void Party::set_index(const char* value,
    size_t size) {
  
  index_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
}
inline std::string* Party::_internal_mutable_index() {
  
  return index_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Party::release_index() {
  // @@protoc_insertion_point(field_release:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
  return index_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Party::set_allocated_index(std::string* index) {
  if (index != nullptr) {
    
  } else {
    
  }
  index_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), index,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.Party.index)
}

// string x = 8;
inline void Party::clear_x() {
  x_.ClearToEmpty();
}
inline const std::string& Party::x() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
  return _internal_x();
}
inline void Party::set_x(const std::string& value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
}
inline std::string* Party::mutable_x() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
  return _internal_mutable_x();
}
inline const std::string& Party::_internal_x() const {
  return x_.Get();
}
inline void Party::_internal_set_x(const std::string& value) {
  
  x_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Party::set_x(std::string&& value) {
  
  x_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
}
inline void Party::set_x(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  x_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
}
inline void Party::set_x(const char* value,
    size_t size) {
  
  x_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
}
inline std::string* Party::_internal_mutable_x() {
  
  return x_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Party::release_x() {
  // @@protoc_insertion_point(field_release:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
  return x_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Party::set_allocated_x(std::string* x) {
  if (x != nullptr) {
    
  } else {
    
  }
  x_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), x,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.Party.x)
}

// .safeheron.proto.CurvePoint g_x = 9;
inline bool Party::_internal_has_g_x() const {
  return this != internal_default_instance() && g_x_ != nullptr;
}
inline bool Party::has_g_x() const {
  return _internal_has_g_x();
}
inline const ::safeheron::proto::CurvePoint& Party::_internal_g_x() const {
  const ::safeheron::proto::CurvePoint* p = g_x_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::CurvePoint&>(
      ::safeheron::proto::_CurvePoint_default_instance_);
}
inline const ::safeheron::proto::CurvePoint& Party::g_x() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.Party.g_x)
  return _internal_g_x();
}
inline void Party::unsafe_arena_set_allocated_g_x(
    ::safeheron::proto::CurvePoint* g_x) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(g_x_);
  }
  g_x_ = g_x;
  if (g_x) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.Party.g_x)
}
inline ::safeheron::proto::CurvePoint* Party::release_g_x() {
  
  ::safeheron::proto::CurvePoint* temp = g_x_;
  g_x_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::safeheron::proto::CurvePoint* Party::unsafe_arena_release_g_x() {
  // @@protoc_insertion_point(field_release:safeheron.proto.multi_party_ecdsa.Li24.Party.g_x)
  
  ::safeheron::proto::CurvePoint* temp = g_x_;
  g_x_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* Party::_internal_mutable_g_x() {
  
  if (g_x_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArena());
    g_x_ = p;
  }
  return g_x_;
}
inline ::safeheron::proto::CurvePoint* Party::mutable_g_x() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.Party.g_x)
  return _internal_mutable_g_x();
}
inline void Party::set_allocated_g_x(::safeheron::proto::CurvePoint* g_x) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(g_x_);
  }
  if (g_x) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(g_x)->GetArena();
    if (message_arena != submessage_arena) {
      g_x = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, g_x, submessage_arena);
    }
    
  } else {
    
  }
  g_x_ = g_x;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.Party.g_x)
}

// repeated string seed = 10;
inline int Party::_internal_seed_size() const {
  return seed_.size();
}
inline int Party::seed_size() const {
  return _internal_seed_size();
}
inline void Party::clear_seed() {
  seed_.Clear();
}
inline std::string* Party::add_seed() {
  // @@protoc_insertion_point(field_add_mutable:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
  return _internal_add_seed();
}
inline const std::string& Party::_internal_seed(int index) const {
  return seed_.Get(index);
}
inline const std::string& Party::seed(int index) const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
  return _internal_seed(index);
}
inline std::string* Party::mutable_seed(int index) {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
  return seed_.Mutable(index);
}
inline void Party::set_seed(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
  seed_.Mutable(index)->assign(value);
}
inline void Party::set_seed(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
  seed_.Mutable(index)->assign(std::move(value));
}
inline void Party::set_seed(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  seed_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
}
inline void Party::set_seed(int index, const char* value, size_t size) {
  seed_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
}
inline std::string* Party::_internal_add_seed() {
  return seed_.Add();
}
inline void Party::add_seed(const std::string& value) {
  seed_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
}
inline void Party::add_seed(std::string&& value) {
  seed_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
}
inline void Party::add_seed(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  seed_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
}
inline void Party::add_seed(const char* value, size_t size) {
  seed_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Party::seed() const {
  // @@protoc_insertion_point(field_list:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
  return seed_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Party::mutable_seed() {
  // @@protoc_insertion_point(field_mutable_list:safeheron.proto.multi_party_ecdsa.Li24.Party.seed)
  return &seed_;
}

// -------------------------------------------------------------------

// SignKey

// string workspace_id = 1;
inline void SignKey::clear_workspace_id() {
  workspace_id_.ClearToEmpty();
}
inline const std::string& SignKey::workspace_id() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
  return _internal_workspace_id();
}
inline void SignKey::set_workspace_id(const std::string& value) {
  _internal_set_workspace_id(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
}
inline std::string* SignKey::mutable_workspace_id() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
  return _internal_mutable_workspace_id();
}
inline const std::string& SignKey::_internal_workspace_id() const {
  return workspace_id_.Get();
}
inline void SignKey::_internal_set_workspace_id(const std::string& value) {
  
  workspace_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SignKey::set_workspace_id(std::string&& value) {
  
  workspace_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
}
inline void SignKey::set_workspace_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  workspace_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
}
inline void SignKey::set_workspace_id(const char* value,
    size_t size) {
  
  workspace_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
}
inline std::string* SignKey::_internal_mutable_workspace_id() {
  
  return workspace_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SignKey::release_workspace_id() {
  // @@protoc_insertion_point(field_release:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
  return workspace_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SignKey::set_allocated_workspace_id(std::string* workspace_id) {
  if (workspace_id != nullptr) {
    
  } else {
    
  }
  workspace_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), workspace_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.SignKey.workspace_id)
}

// int32 threshold = 2;
inline void SignKey::clear_threshold() {
  threshold_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SignKey::_internal_threshold() const {
  return threshold_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SignKey::threshold() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.SignKey.threshold)
  return _internal_threshold();
}
inline void SignKey::_internal_set_threshold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  threshold_ = value;
}
inline void SignKey::set_threshold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_threshold(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.SignKey.threshold)
}

// int32 n_parties = 3;
inline void SignKey::clear_n_parties() {
  n_parties_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SignKey::_internal_n_parties() const {
  return n_parties_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SignKey::n_parties() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.SignKey.n_parties)
  return _internal_n_parties();
}
inline void SignKey::_internal_set_n_parties(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  n_parties_ = value;
}
inline void SignKey::set_n_parties(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_n_parties(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.multi_party_ecdsa.Li24.SignKey.n_parties)
}

// .safeheron.proto.multi_party_ecdsa.Li24.Party local_party = 5;
inline bool SignKey::_internal_has_local_party() const {
  return this != internal_default_instance() && local_party_ != nullptr;
}
inline bool SignKey::has_local_party() const {
  return _internal_has_local_party();
}
inline void SignKey::clear_local_party() {
  if (GetArena() == nullptr && local_party_ != nullptr) {
    delete local_party_;
  }
  local_party_ = nullptr;
}
inline const ::safeheron::proto::multi_party_ecdsa::Li24::Party& SignKey::_internal_local_party() const {
  const ::safeheron::proto::multi_party_ecdsa::Li24::Party* p = local_party_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::multi_party_ecdsa::Li24::Party&>(
      ::safeheron::proto::multi_party_ecdsa::Li24::_Party_default_instance_);
}
inline const ::safeheron::proto::multi_party_ecdsa::Li24::Party& SignKey::local_party() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.SignKey.local_party)
  return _internal_local_party();
}
inline void SignKey::unsafe_arena_set_allocated_local_party(
    ::safeheron::proto::multi_party_ecdsa::Li24::Party* local_party) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(local_party_);
  }
  local_party_ = local_party;
  if (local_party) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.SignKey.local_party)
}
inline ::safeheron::proto::multi_party_ecdsa::Li24::Party* SignKey::release_local_party() {
  
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* temp = local_party_;
  local_party_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::safeheron::proto::multi_party_ecdsa::Li24::Party* SignKey::unsafe_arena_release_local_party() {
  // @@protoc_insertion_point(field_release:safeheron.proto.multi_party_ecdsa.Li24.SignKey.local_party)
  
  ::safeheron::proto::multi_party_ecdsa::Li24::Party* temp = local_party_;
  local_party_ = nullptr;
  return temp;
}
inline ::safeheron::proto::multi_party_ecdsa::Li24::Party* SignKey::_internal_mutable_local_party() {
  
  if (local_party_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::multi_party_ecdsa::Li24::Party>(GetArena());
    local_party_ = p;
  }
  return local_party_;
}
inline ::safeheron::proto::multi_party_ecdsa::Li24::Party* SignKey::mutable_local_party() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.SignKey.local_party)
  return _internal_mutable_local_party();
}
inline void SignKey::set_allocated_local_party(::safeheron::proto::multi_party_ecdsa::Li24::Party* local_party) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete local_party_;
  }
  if (local_party) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(local_party);
    if (message_arena != submessage_arena) {
      local_party = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, local_party, submessage_arena);
    }
    
  } else {
    
  }
  local_party_ = local_party;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.SignKey.local_party)
}

// repeated .safeheron.proto.multi_party_ecdsa.Li24.Party remote_parties = 6;
inline int SignKey::_internal_remote_parties_size() const {
  return remote_parties_.size();
}
inline int SignKey::remote_parties_size() const {
  return _internal_remote_parties_size();
}
inline void SignKey::clear_remote_parties() {
  remote_parties_.Clear();
}
inline ::safeheron::proto::multi_party_ecdsa::Li24::Party* SignKey::mutable_remote_parties(int index) {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.SignKey.remote_parties)
  return remote_parties_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::safeheron::proto::multi_party_ecdsa::Li24::Party >*
SignKey::mutable_remote_parties() {
  // @@protoc_insertion_point(field_mutable_list:safeheron.proto.multi_party_ecdsa.Li24.SignKey.remote_parties)
  return &remote_parties_;
}
inline const ::safeheron::proto::multi_party_ecdsa::Li24::Party& SignKey::_internal_remote_parties(int index) const {
  return remote_parties_.Get(index);
}
inline const ::safeheron::proto::multi_party_ecdsa::Li24::Party& SignKey::remote_parties(int index) const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.SignKey.remote_parties)
  return _internal_remote_parties(index);
}
inline ::safeheron::proto::multi_party_ecdsa::Li24::Party* SignKey::_internal_add_remote_parties() {
  return remote_parties_.Add();
}
inline ::safeheron::proto::multi_party_ecdsa::Li24::Party* SignKey::add_remote_parties() {
  // @@protoc_insertion_point(field_add:safeheron.proto.multi_party_ecdsa.Li24.SignKey.remote_parties)
  return _internal_add_remote_parties();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::safeheron::proto::multi_party_ecdsa::Li24::Party >&
SignKey::remote_parties() const {
  // @@protoc_insertion_point(field_list:safeheron.proto.multi_party_ecdsa.Li24.SignKey.remote_parties)
  return remote_parties_;
}

// .safeheron.proto.CurvePoint g_x = 7;
inline bool SignKey::_internal_has_g_x() const {
  return this != internal_default_instance() && g_x_ != nullptr;
}
inline bool SignKey::has_g_x() const {
  return _internal_has_g_x();
}
inline const ::safeheron::proto::CurvePoint& SignKey::_internal_g_x() const {
  const ::safeheron::proto::CurvePoint* p = g_x_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::CurvePoint&>(
      ::safeheron::proto::_CurvePoint_default_instance_);
}
inline const ::safeheron::proto::CurvePoint& SignKey::g_x() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.multi_party_ecdsa.Li24.SignKey.g_x)
  return _internal_g_x();
}
inline void SignKey::unsafe_arena_set_allocated_g_x(
    ::safeheron::proto::CurvePoint* g_x) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(g_x_);
  }
  g_x_ = g_x;
  if (g_x) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.SignKey.g_x)
}
inline ::safeheron::proto::CurvePoint* SignKey::release_g_x() {
  
  ::safeheron::proto::CurvePoint* temp = g_x_;
  g_x_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::safeheron::proto::CurvePoint* SignKey::unsafe_arena_release_g_x() {
  // @@protoc_insertion_point(field_release:safeheron.proto.multi_party_ecdsa.Li24.SignKey.g_x)
  
  ::safeheron::proto::CurvePoint* temp = g_x_;
  g_x_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* SignKey::_internal_mutable_g_x() {
  
  if (g_x_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArena());
    g_x_ = p;
  }
  return g_x_;
}
inline ::safeheron::proto::CurvePoint* SignKey::mutable_g_x() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.multi_party_ecdsa.Li24.SignKey.g_x)
  return _internal_mutable_g_x();
}
inline void SignKey::set_allocated_g_x(::safeheron::proto::CurvePoint* g_x) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(g_x_);
  }
  if (g_x) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(g_x)->GetArena();
    if (message_arena != submessage_arena) {
      g_x = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, g_x, submessage_arena);
    }
    
  } else {
    
  }
  g_x_ = g_x;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.multi_party_ecdsa.Li24.SignKey.g_x)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Li24
}  // namespace multi_party_ecdsa
}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Li24_2fstruct_2eproto
